specVersion: 0.2.0
name: parascan-subql-starter
version: 1.0.0
description: subql starter for parascan
repository: "https://github.com/parascan/parascan-subql-starter"
schema:
  file: ./schema.graphql

network:
  endpoint: wss://rpc-global.parami.io/ws
  genesisHash: "0x2771615a4f7164aab679fe9d2e8988e119abef2c2df8f456f6ebc76a63298772"

dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
